from business_object.user import Administrator, RegularUser, User
from dao.db_connection import DBConnection
from utils.log_utils import get_logger, log
from utils.singleton import Singleton

logger = get_logger(__name__)


class UserDao(metaclass=Singleton):
    """Data access for users. No hashing of the pwd needed here."""

    @staticmethod
    def _row_to_user(row) -> User:
        """Builds the right User subclass from a database row."""
        if row["is_admin"]:  # à adapter si ta colonne a un autre nom
            return Administrator(
                username=row["username"],
                password=row["password"],
                email=row["email"],
                admin_name=row["username"],
                id_user=row["id_user"],
            )
        return RegularUser(
            username=row["username"],
            password=row["password"],
            email=row["email"],
            visitor_name=row["username"],
            id_user=row["id_user"],
        )

    @log
    def create(self, user: User) -> bool:
        """Saves the user (password already hashed).
        Fills user.id_user with the id generated by the database."""
        res = None
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        'INSERT INTO project."user"(username, password, email, is_admin) '
                        "VALUES (%(username)s, %(password)s, %(email)s, %(is_admin)s) "
                        "RETURNING id_user;",
                        {
                            "username": user.username,
                            "password": user.password,
                            "email": user.email,
                            "is_admin": user.is_admin,
                        },
                    )
                    res = cursor.fetchone()
        except Exception as e:
            logger.error(e)
            raise

        created = False
        if res:
            user.id_user = res["id_user"]
            created = True
        return created

    def find_by_username(self, username: str) -> User | None:
        """Find a user by their username."""
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        'SELECT * FROM project."user" WHERE username = %(username)s;',
                        {"username": username},
                    )
                    res = cursor.fetchone()
        except Exception as e:
            logger.error(e)
            raise

        return self._row_to_user(res) if res else None

    def list_all(self) -> list[User]:
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute('SELECT * FROM project."user" ORDER BY username;')
                    res = cursor.fetchall()
        except Exception as e:
            logger.error(e)
            raise

        return [self._row_to_user(row) for row in res] if res else []

    @log
    def update(self, user: User) -> bool:
        """Update a user in the database.
        Returns True if the update is successful, False otherwise."""
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        'UPDATE project."user" '
                        "   SET username = %(username)s, "
                        "       password = %(password)s, "
                        "       email = %(email)s "
                        " WHERE id_user = %(id_user)s;",
                        {
                            "username": user.username,
                            "password": user.password,
                            "email": user.email,
                            "id_user": user.id_user,
                        },
                    )
                    nb_affected_rows = cursor.rowcount
        except Exception as e:
            logger.error(e)
            raise

        return nb_affected_rows == 1

    @log
    def delete(self, user: User) -> bool:
        """Delete a user from the database.
        Returns True if the user was deleted, False otherwise."""
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        'DELETE FROM project."user" WHERE id_user = %(id_user)s;',
                        {"id_user": user.id_user},
                    )
                    res = cursor.rowcount
        except Exception as e:
            logger.error(e)
            raise

        return res > 0

    @log
    def login(self, username: str, password: str) -> User:
        """Login using username and password.
        Args:
            username (str)
            password (str)
        Returns:
            User or None
        """
        res = None
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "SELECT *                               "
                        "  FROM user                            "
                        " WHERE username = %(username)s         "
                        "   AND password = %(password)s;        ",
                        {"username": username, "password": password},
                    )
                    res = cursor.fetchone()
        except Exception as e:
            logger.error(e)
            raise

        user = None

        if res:
            user = User(
                username=res["username"],
                password=res["password"],
                email=res["email"],
                id_user=res["id_user"],
            )

        return user

    @log
    def find_by_id(self, id_user: int) -> User | None:
        """Find a user by their id."""
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        'SELECT * FROM project."user" WHERE id_user = %(id_user)s;',
                        {"id_user": id_user},
                    )
                    res = cursor.fetchone()
        except Exception as e:
            logger.error(e)
            raise

        return self._row_to_user(res) if res else None

    @log
    def record_connection(self, id_user: int) -> None:
        """Records a successful connection."""
        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(
                        "INSERT INTO project.connectionlog (id_user, connection_moment) "
                        "VALUES (%(id_user)s, NOW());",
                        {"id_user": id_user},
                    )
        except Exception as e:
            logger.error(e)
            raise

    @log
    def get_connection_history(self, id_user: int | None = None, limit: int = 100) -> list[dict]:
        """Returns the most recent connections (of one user or of everybody)."""
        query = (
            "SELECT c.id_connection, c.id_user, u.username, c.connection_moment "
            "  FROM project.connectionlog c "
            '  JOIN project."user" u ON u.id_user = c.id_user '
        )
        params = {"limit": limit}
        if id_user is not None:
            query += " WHERE c.id_user = %(id_user)s "
            params["id_user"] = id_user
        query += " ORDER BY c.connection_moment DESC LIMIT %(limit)s;"

        try:
            with DBConnection().connection as connection:
                with connection.cursor() as cursor:
                    cursor.execute(query, params)
                    rows = cursor.fetchall()
        except Exception as e:
            logger.error(e)
            raise

        return [
            {
                "id_connection": r["id_connection"],
                "id_user": r["id_user"],
                "username": r["username"],
                "connection_moment": r["connection_moment"],
            }
            for r in rows
        ]
