---
bibliography: refs.bib
citeproc: false
nocite: "@*"
format:
  html:
    code-tools: true
  typst:
    papersize: a4
    margin:
      x: 1.5cm
      y: 2.0cm
    section-numbering: 1.1.a
    mainfont: "Libertinus Serif"
    fontsize: 11pt
---


```{=typst}
#import "model.typ": project_template

#show: body => project_template(
  title: [Analysis Report on the NEO - Watch Project],
  team: [Équipe 7],
  authors: ([Tristan Cabre], [Gabrielle Causse], [Albane Krob], [Noé Chauvin]),
  tutor: [M. Ricciardi],
  project: [Projet Informatique de 2ème année - Année 2026-2027],
  body
)
```

## Introduction {.unnumbered}

```{=typst} 
#lorem(100)
```

{{< pagebreak >}}

## Section 1 : Architecture of the Application

### Subsection 1.1 : Class Diagram
[Conceptual conception of the application Neo-Watch ]{.underline}\

Neo-Watch is an application dedicated to the monitoring of Near Earth Objects (NEOs). Its purpose is to let people search and follow NEOs, keep track on how their distance to Earth changes over time, and be alerted immediately when an object comes close to Earth. To manage access rights and demanded features in the application, we will separate administrators who are given extra rights to manage the platform itself (accounts, connection history, and the underlying NEO database) from common users, called visitors in this architecture. 

The conceptual model is built directly from the class diagram of the application. It is organised in two complementary readings: first, the layered architecture that structures how the code is organised; second, the domain (business) classes that carry the actual concepts of the application, Users, NEOs, Alerts, Favourites, and their history. 

[Classes for the Business part]{.underline}\

The domain classes are essential for this application. 

1.1 Users 

Every person who uses the application is represented by the class User, which represents what is common to all accounts: a pseudo, a password which is always stored hashed, thanks to the methods hash and check for the password. An email address is also stored and used to receive alerts. Two particular cases extend this class: 

Visitor: This user is an ordinary visitor of the application. They can create an account, log in, save a password, build a list of favourite NEOs, receive notifications and search the database. 

Administrator: This particular user inherits everything a Visitor can do, and additionally gets privileged actions. The administrators consulting the loggin history of the Neo, watch application, and searching, updating or deleting any account of a visitor. 

This inheritance relationship (User <- Visitor and Administrator). It could be said that an Administrator is a User with extended rights. 

1.2 Near Earth Objects (NEO) 

The class Neo represents a Near Earth Object, with its descriptive characteristics: name, weight, size, composition, rarity, origin, its closest recorded day, and a distance to Earth. This distance is not a fixed, it evolves over time as the object continues its trajectory in the NASA database, which is precisely why it is built so that there can be a mechanism to keep track of it. 

The NeoDistanceHistory class enables to folow how a NEO's distance to Earth evolves after each update of the database. Each Neo should own exactly one NeoDistanceHistory object. It is a component of the Neo itself, responsible for recording the evolution of the distance to Earth. Internally, it keeps a list of records (a date to reference the distance to Earth) which will give the opporutnity for a User to reconstruct its evolution, approach or leave over time. 

This design keeps a clean separation of concerns: the Neo class describes what the object is, while NeoDistanceHistory describes how its distance behaves through time which will be the information Favourites and Alert rely on. 

1.3 Favourites 

A User can build a personal list of favourite NEOs through the Favourites class. Each Favourites entry links one User to one Neo. 

1.4 Alerts and Notifications 

Every User can define one or more Alert entries, each one relying on a condition to trigger the notification. 

 

 

 

### Subsection 1.2

{{< pagebreak >}}

## Section 2

2.4 Physical data model

The physical data model represents the different databases used to operate the application. Each table stores a specific object. The tables are linked to one another through a primary key/foreign key system. The cardinalities are directly indicated on the diagram.

The two main objects in this application are users and asteroids, the latter also forming the core of the physical data model. The “NEO” table depends directly on NASA’s API, whereas the “User” table stores information (pseudo, password, email,...) about the different users registered on the application.

The favourites and alerts are stored in separate tables so that they are not lost each time the data is refreshed through the API. These two tables also establish the link between users and the asteroids. The other tables store the information required to implement the functionalities specified in the requirements.

For example, the requirements state: “For each favourite NEO, a history of its distance from Earth must be maintained.” We therefore need a “NeoDistanceHistory” table linked to the “Neo” table, which stores pairs of values consisting of a date and a distance. We choose the type of "distance" to be float because it is easier to build statistics then.

Another functionality that requires additional data tables is the history feature. We need to store all queries in a database, along with the corresponding user and the date on which the query was made. To achieve this, we defined two data tables: one for the search history (“SearchHistory”) and the other for the users’ connection history (“ConnectionLog”).

{{< pagebreak >}}

## Bibliography


{{< pagebreak >}}

## Conclusion {.unnumbered}


{{< pagebreak >}}

## Annexes {.unnumbered}


{{< pagebreak >}}